# Generated by Django 6.0.4 on 2026-04-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default='Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(default='Comment'),
        ),
    ]
